<?php
/**
 * This template displays the single Product
 *
 * @package genesis_connect_woocommerce
 * @version 0.9.8
 *
 * Note for customisers/users: Do not edit this file!
 * ==================================================
 * If you want to customise this template, copy this file (keep same name) and place the
 * copy in the child theme's woocommerce folder, ie themes/my-child-theme/woocommerce
 * (Your theme may not have a 'woocommerce' folder, in which case create one.)
 * The version in the child theme's woocommerce folder will override this template, and
 * any future updates to this plugin won't wipe out your customisations.
 *
 */

/** Enqueue JS scripts */
add_action( 'wp_enqueue_scripts', 'ap_fixed_summary' );
function ap_fixed_summary() {
    wp_enqueue_script( 'fixed-summary', get_bloginfo( 'stylesheet_directory' ) . '/assets/scripts/min/fixed-summary.min.js', array( 'jquery' ), CHILD_THEME_VERSION );
    wp_enqueue_script( 'div-toggle', get_bloginfo( 'stylesheet_directory' ) . '/assets/scripts/min/div-toggle.min.js', array( 'jquery' ), CHILD_THEME_VERSION );
}

//* Force full-width-content layout setting
add_filter( 'genesis_pre_get_option_site_layout', '__genesis_return_full_width_content' );

/** Remove default Genesis loop */
remove_action( 'genesis_loop', 'genesis_do_loop' );

/** Remove WooCommerce breadcrumbs */
remove_action( 'woocommerce_before_main_content', 'woocommerce_breadcrumb', 20 );

/** Uncomment the below line of code to add back WooCommerce breadcrumbs */
//add_action( 'genesis_before_loop', 'woocommerce_breadcrumb', 10, 0 );

/** Remove Woo #container and #content divs */
remove_action( 'woocommerce_before_main_content', 'woocommerce_output_content_wrapper', 10 );
remove_action( 'woocommerce_after_main_content', 'woocommerce_output_content_wrapper_end', 10 );

// Fixed product summary tweaks

add_action('woocommerce_single_product_summary', 'ap_fixed_summary_open_div', 4);
function ap_fixed_summary_open_div() {
    echo '<div class="fixed-summary">';
}

add_action('woocommerce_single_product_summary', 'ap_fixed_summary_close_div', 51);
function ap_fixed_summary_close_div() {
    echo '</div>';
}

remove_action( 'business_page_header', 'business_page_title', 10 );
add_action( 'woocommerce_single_product_summary', 'ap_single_artwork_artist_name', 5 );
add_action( 'woocommerce_single_product_summary', 'genesis_do_post_title', 5 );
function ap_single_artwork_artist_name() {
    echo '<span class="fixed-summary__artist-name">' . get_field('artista')[0]->post_title .'</span>';
}

remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_rating', 10 );

// Move price
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_price', 10 );
add_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_price', 25 );

// Remove add to cart button, add contact button instead
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_add_to_cart', 30 );
add_action( 'woocommerce_single_product_summary', 'ap_single_product_contact_button', 30 );
function ap_single_product_contact_button () {
    ?>
    <a class="button fixed-summary__button" href="#"><?php _e('Contact', 'business-pro') ?></a>
    <?php
}

add_action('woocommerce_single_product_summary', 'ap_fixed_summary_shipping_info', 30);
function ap_fixed_summary_shipping_info() {
        ?>
        <div class="fixed-summary__services--title">
            <span><?php _e('Our Services', 'business-pro') ?></span>
        </div>
        <div class="fixed-summary__services--list">
            <ul>
                <li>Questions about this work?</li>
                <li>Interested in other works by this artist? </li>
                <li>Want to pay in installments?</li>
                <li>Prova la tua opera installata . Guarda i nostri lavori</li>
            </ul>
        </div>
         <a class="button button--white fixed-summary__button" href="#"><?php _e('Contact Us', 'business-pro') ?></a>
        <?php
}

// Remove single meta (categories, tags ect.)
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_meta', 40 );

/** Custom FlexSlider Navigation **/

add_theme_support( 'wc-product-gallery-lightbox' );
add_theme_support( 'wc-product-gallery-slider' );

// Remove quantity in all product types
function ap_wc_remove_all_quantity_fields( $return, $product ) {
    return true;
}
add_filter( 'woocommerce_is_sold_individually', 'ap_wc_remove_all_quantity_fields', 10, 2 );

// Update WooCommerce Flexslider options

add_filter( 'woocommerce_single_product_carousel_options', 'ap_update_woo_flexslider_options' );
function ap_update_woo_flexslider_options( $options ) {
	/* properties here: https://github.com/woocommerce/FlexSlider/wiki/FlexSlider-Properties */
    $options['directionNav'] = true;
    $options['touch'] = true;
    $options['controlNav'] = true;
    $options['smoothHeight'] = true;
    $options['animateHeight'] = true;
    
    return $options;
}

// /* Share icons on product */
//
// add_action('woocommerce_share', 'ap_add_social_buttons' );
// function ap_add_social_buttons() {
//     genesis_share_icon_output( 'header', array(  'facebook', 'googlePlus', 'pinterest' ) );
// }

/**
 * Remove existing tabs from single product pages.
 */
function ap_remove_woocommerce_product_tabs( $tabs ) {
	unset( $tabs['description'] );
	unset( $tabs['reviews'] );
	unset( $tabs['additional_information'] );
	return $tabs;
}
add_filter( 'woocommerce_product_tabs', 'ap_remove_woocommerce_product_tabs', 98 );

/**
 * Hook in each tabs callback function after single content.
 */
add_action( 'woocommerce_after_single_product_summary', 'ap_custom_woocommerce_product_description_tab' );
/*add_action( 'woocommerce_after_single_product_summary', 'ap_custom_comments_template' );*/
function ap_custom_woocommerce_product_description_tab() {
    ?>
    <div class="single-product-additional-info">
        <div id="product-details" style="position:absolute;top:-10rem;"></div>

            <h2 class="about-the-work"><?php _e('About The Work', 'business-pro'); ?></h2>
            <div class="single-product-additional-info__artwork-content">
                <?php genesis_do_post_content(); ?>
            </div>
            <div class="option-heading">
                <h2 class="option-heading--title"><?php _e('About', 'business-pro'); get_field('artista')[0]->post_title; ?></h2>
                <div class="arrow-up">-</div>
                <div class="arrow-down">+</div>
            </div>
            <div class="option-content">
			    <div id="single-product-description">
				    <h2 class="option-content__title">
                        <?php 
                        $artistName = get_field('artista')[0]->post_title;
                        printf( __('About %s', 'business-pro'), $artistName );
                        ?>
                        
                    </h2>
                    <?php
                    $artist_page_ID = get_field('artista')[0]->ID;
                    $artist_post_content = apply_filters('the_content', get_post_field('post_content', $artist_page_ID ));
                    echo $artist_post_content;
                    ?>
                    <a class="option-content__artist-link" href="<?php echo get_permalink($artist_page_ID); ?>"><?php printf( __('Go to %s artist page >', 'business-pro'), $artistName ); ?></a>
                    <div class="option-content__space"></div>
			   </div>
		    </div>
            
            <?php ap_output_artist_other_works(); ?>
            
    </div>
    <div id="stop-summary" style="width:100%;float:left;"></div>
    <?php
}

/**
 * Remove related products output
 */
remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_output_related_products', 20 );

add_action( 'woocommerce_after_single_product_summary', 'ap_artwork_custom_related', 20 );
function ap_artwork_custom_related() {
    ap_output_artist_related_works_slider();
    ap_output_artist_related_articles();
    ap_output_artist_recentely_viewed();
}

function ap_output_artist_other_works() {
    $productID = get_the_ID();
    $artistName = get_field('artista')[0]->post_title;
    $artistID = get_field('artista')[0]->ID;

    $relatedWorks = new WP_Query(array(
        'posts_per_page' => 6,
        'post_type' => 'product',
        'orderby' => 'rand',
        'order' => 'ASC',
        'meta_query' => array(
            array(
                'key' => 'artista',
                'compare' => 'LIKE',
                'value' => '"' . $artistID . '"'
            )
        )
    ));

    if ($relatedWorks->have_posts()) {
        // Check if there are other works by the artist other than the one we are currently processing
        // If there are no works, return false and exit before outputting the related works section
        while( $relatedWorks->have_posts()) {
            $relatedWorks->the_post();
            if (get_the_ID() !== $productID) {
                $hasPosts = true;
            }
            if (!$hasPosts) {
                wp_reset_postdata();
                return false;
            }
        }
        ?>
        <div class="option-heading">
            <h2 class="option-heading--title"><?php printf( __('Other Works by %s', 'business-pro'), $artistName ); ?></h2>
            <div class="arrow-up">-</div>
            <div class="arrow-down">+</div>
        </div>
        <div class="option-content">
            <div id="single-product-description">
                <h2 class="option-content__title option-content__title--bigger"><?php printf( __('Other Works by %s', 'business-pro'), $artistName ); ?>
                    
                </h2>
        <?php 
        echo '<ul class="products columns-3">';
        $counter = 1;
        while( $relatedWorks->have_posts()) {
            $relatedWorks->the_post();
            $colClass = '';
            if ( $counter % 3 == 0) {
                $colClass = 'last';
            } 
            if ( (($counter % 3) + 1) == 2) {
                $colClass = 'first';
            } 
            if (get_the_ID() !== $productID) {
                ?>
                <li class="product <?php echo $colClass; ?> type-product status-publish has-post-thumbnail entry instock purchasable">
                    <a class="woocommerce-LoopProduct-link woocommerce-loop-product__link" href="<?php the_permalink(); ?>">
                    <?php 
                    the_post_thumbnail('woocommerce_thumbnail');
                    echo '<span class="fixed-summary__artist-name">' . get_field('artista')[0]->post_title .'</span><br/>';
                    the_title();
                    the_excerpt(); 
                    ?>
                    </a>
                </li>
                <?php
                $counter++;
            }
        }
        echo '</ul>';
        echo '</div></div>';
    }

    wp_reset_postdata();

}
function ap_output_artist_related_works_slider() {
    $artistID = get_field('artista')[0]->ID;
    // Check if there are related posts
    $regioneArtista = get_field('regione', $artistID);
    $hasPosts = do_shortcode('[shortcode-flexslider ulid="artwork-detail-slider" location="carousel" animation="slide" slideshowspeed="6" regione="'.$regioneArtista.'" artist_ID='.$artistID.']');
    if ($hasPosts) {
        echo '<div style="display:block;width:100%;float:left;position:relative;">';
        echo do_shortcode('[shortcode-flexslider ulid="artwork-detail-slider" location="carousel" animation="slide" slideshowspeed="6" regione="Italia" artist_ID='.$artistID.']');
        echo '</div>';
    }
}
function ap_output_artist_related_articles() {
    
}
function ap_output_artist_recentely_viewed() {
    
}

add_action( 'genesis_loop', 'gencwooc_single_product_loop' );
/**
 * Displays single product loop
 *
 * Uses WooCommerce structure and contains all existing WooCommerce hooks
 *
 * Code based on WooCommerce 1.5.5 woocommerce_single_product_content()
 * @see woocommerce/woocommerce-template.php
 *
 * @since 0.9.0
 */
function gencwooc_single_product_loop() {

	do_action( 'woocommerce_before_main_content' );

	// Let developers override the query used, in case they want to use this function for their own loop/wp_query
	$wc_query = false;

	// Added a hook for developers in case they need to modify the query
	$wc_query = apply_filters( 'gencwooc_custom_query', $wc_query );

	if ( ! $wc_query) {

		global $wp_query;

		$wc_query = $wp_query;
	}

	if ( $wc_query->have_posts() ) while ( $wc_query->have_posts() ) : $wc_query->the_post(); ?>

		<?php do_action('woocommerce_before_single_product'); ?>

		<div itemscope itemtype="http://schema.org/Product" id="product-<?php the_ID(); ?>" <?php post_class(); ?>>

			<?php do_action( 'woocommerce_before_single_product_summary' ); ?>

			<div class="summary">

				<?php do_action( 'woocommerce_single_product_summary'); ?>

			</div>

			<?php do_action( 'woocommerce_after_single_product_summary' ); ?>

		</div>

		<?php do_action( 'woocommerce_after_single_product' );

	endwhile;

	do_action( 'woocommerce_after_main_content' );
}

genesis();
